Headers:  # in pixels
  Table:
    name: 800
    ndim: 30
    shape: 100
    dimensions: 200
    units: 100
    dtype: 100
    attributes: 400
  Filemenu:
    Name: 1000
    Size: 130
    Type: 130
    Date Modified: 140

Startingsize:
  Mainwindow:  # in pixels,
    width: 1800  # should be equal or larger than sum of Headers
    height: 800
  2Dplot:  # in inches
    width: 5
    height: 5
    dpi: 150
  3Dplot:  # in inches
    width: 4
    height: 4
    dpi: 150
  1Dplot:  # in inches
    width: 4
    height: 4
    dpi: 150
  Filemenu:  # in pixels
    width: 1400
    height: 600

Tableview:
  location: bottom  # top, left, right, bottom
  stacking: vertical  # horizontal, vertical
  tabbing: True  # False, True

# not necessarily needed. One can set the colorscheme for the app and for the plots here. The
# plots can be configured with the normal rc file in matplotlib, or with standard matplotlib style sheets.
Colorscheme:
  App: dark   # dark, light
  plots: [stylesheet.mplstyle] #seaborn-ticks, classic, Solarize_Light2, dark_background] #, seaborn-colorblind]
  #plots: dark_background
  # any combination from plt.style.available, check also here:
  # https://matplotlib.org/3.2.1/gallery/style_sheets/style_sheets_reference.html
  # if an own file is set, this needs to be last and located in the same folder as app

# not necessarily needed. This is to override colors in "dark" color scheme for "App"
Colors:
  WHITE: [245, 245, 245]  # --> font in tree, table, buttons
  BLACK: [30, 30, 0]  # --> font in highlighted tree and table
  BRIGHT: [255, 0, 0]  # for bright text, but not used now
  PRIMARY: [80, 80, 80]  #  --> main layout, also in figures
  SECONDARY: [60, 60, 60]   # --> tree and table background
  TERTIARY: [142, 142, 170]  # --> highlighted in tree and table