Headers:  # in pixels
  Table:
    name: 700
    ndim: 30
    shape: 100
    dimensions: 200
    units: 100
    dtype: 100
    attributes: 400
  Filemenu:
    Name: 1000
    Size: 130
    Type: 130
    Date Modified: 140

Startingsize:
  Fontsize: 9
  Mainwindow:  # in pixels,
    width: 1500  # should be equal or larger than sum of Headers
    height: 600
  2Dplot:  # in inches
    width: 5
    height: 5
    dpi: 150
  3Dplot:  # in inches
    width: 4
    height: 4
    dpi: 150
  1Dplot:  # in inches
    width: 4
    height: 4
    dpi: 150
  Filemenu:  # in pixels
    width: 1400
    height: 600

Tableview:
  location: bottom  # top, left, right, bottom
  stacking: horizontal  # horizontal, vertical
  tabbing: True  # False, True

# not necessarily needed. One can set the colorscheme for the app and for the plots here. The
# plots can be configured with the normal rc file in matplotlib, or with standard matplotlib style sheets.
Colorscheme:
  App: dark   # dark, light
  #plots: [stylesheet.mplstyle] #seaborn-ticks, classic, Solarize_Light2, dark_background] #, seaborn-colorblind]
  #plots: dark_background
  # any combination from plt.style.available, check also here:
  # https://matplotlib.org/3.2.1/gallery/style_sheets/style_sheets_reference.html
  # if an own file is set, this needs to be last and located in the same folder as app

# not necessarily needed. This is to override colors in "dark" color scheme for "App"
Colors:
  WHITE: [245, 245, 215]  # --> font in tree, table, buttons
  BLACK: [50, 50, 80]  # --> font in highlighted tree and table
  BRIGHT: [255, 0, 0]  # for bright text, but not used now
  PRIMARY: [60, 60, 110]  #  --> main layout, also in figures
  SECONDARY: [40, 40, 80]   # --> tree and table background
  TERTIARY: [192, 192, 230]  # --> highlighted in tree and table

Plotsettings:
  scatter_dot_size: 0.5
  country_line_color: gray
  country_line_thickness: 0.4
