Headers:  # in pixels
  Table:
    name: 900
    ndim: 30
    shape: 100
    dimensions: 200
    units: 100
    dtype: 100
    attributes: 400
  Filemenu:
    Name: 1000
    Size: 130
    Type: 130
    Date Modified: 140

Startingsize:
  Mainwindow:  # in pixels,
    width: 1800  # should be equal or larger than sum of Headers
    height: 400
  2Dplot:  # in inches
    width: 5
    height: 5
    dpi: 150
  3Dplot:  # in inches
    width: 4
    height: 4
    dpi: 150
  1Dplot:  # in inches
    width: 4
    height: 4
    dpi: 150
  Filemenu:
    width: 1400
    height: 600