Headers:  # in pixels
  name: 400
  ndim: 30
  shape: 100
  dimensions: 200
  units: 100
  dtype: 100
  attributes: 400

Startingsize:
  Mainwindow:  # in pixels,
    width: 1400  # should be equal or larger than sum of Headers
    height: 400
  2Dplot:  # in inches
    width: 5
    height: 5
    dpi: 150
  3Dplot:  # in inches
    width: 4
    height: 4
    dpi: 150
  1Dplot:  # in inches
    width: 4
    height: 4
    dpi: 150